### PR TITLE
Null pointer exception if there is null in hstore type column

### PR DESCRIPTION
**Pull request by smsufyian**

### CODE REVIEW

**Comment by smsufyian** [comment]
@The-Alchemist can you please take a look at the CI configuration , it works locally but some CI checks are failing .

**Comment by smsufyian** [comment]
@The-Alchemist during the CI , it is not able to make connection to the database , however I have provided the solution for the issue as well . The impdeiment left is the issue with the CI configs , can you take a look at it ?

**Comment by smsufyian** [comment]
@The-Alchemist can you please review it and then merge it ?

**Comment by The-Alchemist** [comment]
merged and released as version 1.0.21.

thank you, @SyedMuhammadSufyian ! :)

**Pull request merged**
